{% set name = "typing-inspection" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/typing_inspection-{{ version }}.tar.gz
  sha256: 6ae134cc0203c33377d43188d4064e9b357dba58cff3185f22924610e70a9d28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.12.0

test:
  imports:
    - typing_inspection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Runtime typing introspection tools
  home: https://github.com/pydantic/typing-inspection
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
